# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "packages/crypto_support"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/openssl_crypto_common_ffi"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/openssl_crypto_flutter_libs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/openssl_crypto_flutter_libs/example"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
