name: tekartik_crypto_support
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  path: ^1.8.0
  ffigen:
  process_run:
  dev_test:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
