name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_crypto_support:
    path: ../packages/crypto_support
dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  pedantic:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'

