name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  tekartik_crypto_support:
    path: ../packages/crypto_support
dev_dependencies:
  path:
  pub_semver:
  dev_build:
  process_run:
  pedantic:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

