name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_crypto_support:
    path: ../packages/crypto_support
dev_dependencies:
  path:
  pub_semver:
  dev_test:
  process_run:
  pedantic:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

